### ISSUE TITLE
Import issues with ajv module

### ISSUE THREAD

**Issue by DominicGBauer** [anttiviljami/openapi-backend#211]
Hi I am experiencing the following issues when upgrading to 4+ in the `validation.d.ts`

```
node_modules/openapi-backend/validation.d.ts(1,8): error TS1259: Module '"/node_modules/ajv/lib/ajv"' can only be default-imported using the 'esModuleInterop' flag
[0] node_modules/openapi-backend/validation.d.ts(133,60): error TS2315: Type 'ValidateFunction' is not generic.
[0] node_modules/openapi-backend/validation.d.ts(163,60): error TS2315: Type 'ValidateFunction' is not generic.
```

It seems to be an issue with the way ajv is imported and not really sure about the ValidateFunction
